#
# docker-compose up -d
#

services:

    dependencyfinder:
        ports:
          - 8080:8080
        volumes:
          - ./lib/DependencyFinder.jar:/code/DependencyFinder.jar:ro
          - ./df.xml:/code/df.xml:ro
