@startuml

skin rose
skinparam style strictuml
skinparam backgroundColor transparent

title Chain of Strategies With -code Switch

object "baseStrategy : CodeDifferenceStrategy" as baseStrategy #lightgreen

object "strategy : APIDifferenceStrategy" as strategy #lightgreen
strategy --> baseStrategy

object ": DifferenceFactory" as factory
factory -> strategy

@enduml
