@startuml

skin rose
skinparam backgroundColor transparent
skinparam componentStyle uml1

node ":lib" as lib {

    [main] as lib_main

    [test] as lib_test #lightgreen
    lib_main <. lib_test

    [jacoco] as lib_jacoco #lightgrey
    lib_main .[hidden].> lib_jacoco

}

node ":integration-tests" as integration_tests {

    [main] as integration_tests_main #transparent

    [test] as integration_tests_test #lightgreen
    integration_tests_main <. integration_tests_test

    [jacoco] as integration_tests_jacoco #lightgrey
    integration_tests_main .[hidden].> integration_tests_jacoco

}
lib <.. integration_tests

node ":fit-tests" as fit_tests {

    [main] as fit_tests_main #transparent

    [test] as fit_tests_test #lightgreen
    fit_tests_main <. fit_tests_test

    [jacoco] as fit_tests_jacoco #lightgrey
    fit_tests_main .[hidden].> fit_tests_jacoco

}
lib <.. fit_tests

node ":webapp" as webapp {

    [main] as webapp_main

    [test] as webapp_test #lightgreen
    webapp_main <. webapp_test

    [jacoco] as webapp_jacoco #lightgrey
    webapp_main .[hidden].> webapp_jacoco

}
lib <.. webapp

node ":code-coverage-report" as code_coverage_report {

    [jacoco-report-aggregation] as code_coverage_report_jacoco_report_aggregation #lightgrey
    code_coverage_report_jacoco_report_aggregation .up.> lib_jacoco
    code_coverage_report_jacoco_report_aggregation .up.> integration_tests_jacoco
    code_coverage_report_jacoco_report_aggregation .up.> fit_tests_jacoco
    code_coverage_report_jacoco_report_aggregation .up.> webapp_jacoco

}

@enduml
