@startuml

skin rose
skinparam style strictuml
skinparam backgroundColor transparent

set separator none
hide empty members

package com.jeantessier.classreader {

    interface classreader.Visitor as "Visitor" <<interface>>

    abstract class classreader.VisitorBase as "VisitorBase"
    classreader.Visitor <|.. classreader.VisitorBase

    abstract class classreader.Printer as "Printer"
    classreader.VisitorBase <|-- classreader.Printer

    class classreader.DeprecationPrinter as "DeprecationPrinter"
    classreader.Printer <|-- classreader.DeprecationPrinter

    class classreader.TextPrinter as "TextPrinter"
    classreader.Printer <|-- classreader.TextPrinter

    class classreader.XMLPrinter as "XMLPrinter"
    classreader.Printer <|-- classreader.XMLPrinter

    class classreader.JSONPrinter as "JSONPrinter" #lightgreen
    classreader.Printer <|-- classreader.JSONPrinter
    classreader.DeprecationPrinter -[hidden]-> classreader.JSONPrinter

    class classreader.YAMLPrinter as "YAMLPrinter" #lightgreen
    classreader.Printer <|-- classreader.YAMLPrinter
    classreader.TextPrinter -[hidden]-> classreader.YAMLPrinter

}

package com.jeantessier.dependency {

    interface dependency.Visitor as "Visitor" <<interface>>

    abstract class dependency.VisitorBase as "VisitorBase"
    dependency.Visitor <|.. dependency.VisitorBase

    abstract class dependency.Printer as "Printer"
    dependency.VisitorBase <|-- dependency.Printer

    class dependency.HTMLPrinter as "HTMLPrinter"
    dependency.Printer <|-- dependency.HTMLPrinter

    class dependency.TextPrinter as "TextPrinter"
    dependency.Printer <|-- dependency.TextPrinter

    class dependency.XMLPrinter as "XMLPrinter"
    dependency.Printer <|-- dependency.XMLPrinter

    class classreader.JSONPrinter as "JSONPrinter" as "JSONPrinter" #lightgreen
    dependency.Printer <|-- dependency.JSONPrinter
    dependency.HTMLPrinter -[hidden]-> dependency.JSONPrinter

    class dependency.YAMLPrinter as "YAMLPrinter" #lightgreen
    dependency.Printer <|-- dependency.YAMLPrinter
    dependency.TextPrinter -[hidden]-> dependency.YAMLPrinter

}

package com.jeantessier.diff {

    interface diff.Visitor as "Visitor" <<interface>>

    abstract class diff.VisitorBase as "VisitorBase"
    diff.Visitor <|.. diff.VisitorBase

    abstract class diff.Printer as "Printer"
    diff.VisitorBase <|-- diff.Printer

    class diff.ClassReport as "ClassReport"
    diff.Printer <|-- diff.ClassReport

    class diff.Report as "Report"
    diff.Printer <|-- diff.Report

}

package com.jeantessier.metrics {

    interface MeasurementVisitor <<interface>>

    abstract class metrics.Printer as "Printer"
    MeasurementVisitor <|.. metrics.Printer

    class metrics.CSVPrinter as "CSVPrinter"
    metrics.Printer <|-- metrics.CSVPrinter

    class metrics.TextPrinter as "TextPrinter"
    metrics.Printer <|-- metrics.TextPrinter

    class metrics.XMLPrinter as "XMLPrinter"
    metrics.Printer <|-- metrics.XMLPrinter

    class metrics.JSONPrinter as "JSONPrinter" #lightgreen
    metrics.Printer <|-- metrics.JSONPrinter
    metrics.CSVPrinter -[hidden]-> metrics.JSONPrinter

    class metrics.YAMLPrinter as "YAMLPrinter" #lightgreen
    metrics.Printer <|-- metrics.YAMLPrinter
    metrics.TextPrinter -[hidden]-> metrics.YAMLPrinter

}

@enduml
